name: demo-project
services:
  crud:
    build:
      context: .
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    profiles: [ "database" ]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${KONG_PG_DATABASE:-kong}",
          "-U",
          "${KONG_PG_USER:-kong}"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    expose:
      - 5432

secrets:
  kong_postgres_password:
    file: ./secrets/postgres_password

volumes:
  db_data: {}
